name: cmake

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        c_compiler:
        - gcc
        - aarch64-linux-gnu-gcc
        - cl
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: aarch64-linux-gnu-gcc
            cpp_compiler: aarch64-linux-gnu-g++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: aarch64-linux-gnu-gcc
          - os: windows-latest
            c_compiler: cl
          - os: ubuntu-latest
            c_compiler: cl
          - os: ubuntu-latest
            c_compiler: aarch64-linux-gnu-gcc

    steps:
    - uses: actions/checkout@v4

    - name: Install Ubuntu Packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        if [ '${{ matrix.c_compiler }}' == 'aarch64-linux-gnu-gcc' ]
        then
          sudo dpkg --add-architecture arm64
          sudo apt clean
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt install -y libsdl2-dev:arm64 libsdl2-ttf-dev:arm64
        else
          sudo apt update
          sudo apt install -y libsdl2-dev libsdl2-ttf-dev
        fi
        sudo apt install -y inkscape

    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Release

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest --build-config Release

    - name: Pack
      working-directory: ${{ github.workspace }}/build
      run: cpack --build-config Release
